namespace UpBeat.Models;

/// <summary>
/// A playlist found on a music source, which can be imported into UpBeat.
/// </summary>
/// <param name="Id">Identifier of the playlist on its source.</param>
/// <param name="Title">Title of the playlist.</param>
/// <param name="Author">Author of the playlist, or <c>null</c> if unknown (e.g. playlists generated by YouTube).</param>
/// <param name="ThumbnailUrl">URL of a small thumbnail image, or <c>null</c> if none.</param>
public record PlaylistResult(string Id, string Title, string? Author, string? ThumbnailUrl);
